{{- /*
在模板开始处添加调试信息
*/}}
{{- range .Values.enabledRpcs }}
{{- $ctx := dict "name" . "Files" $.Files }}
{{- $rpcValues := fromYaml (include "rpcs.getValues" $ctx) }}
{{- $mergedValues := merge
    (dict)
    ($rpcValues.hpa | default dict)
    ($.Values.hpa | default dict)
}}
{{- $rpcOriginName := $rpcValues.deployment.name }}
{{- $rpcName := $rpcOriginName | lower | replace "." "-" | replace "_" "-" }}
{{- $rpcInstance := printf "slp-functor-rpc-%s" $rpcName }}
{{- /* 调试信息 */ -}}
{{- if $.Values.debug }}
{{- printf "\nDebug info for command: %s" . | nindent 0 }}
{{- printf "\nCommand Values:" | nindent 0 }}
{{- toYaml $rpcValues | nindent 2 }}
{{- printf "\nMerged Values:" | nindent 0 }}
{{- toYaml $mergedValues | nindent 2 }}
{{- end }}
---
{{- if $mergedValues.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $rpcInstance }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    role: rpc
{{- with $mergedValues }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $rpcInstance }}-deploy
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  {{- if .metrics.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .metrics.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if .metrics.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .metrics.memory.targetAverageUtilization }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .behavior.scaleDown.policies | nindent 8 }}
    scaleUp:
      selectPolicy: {{ .behavior.scaleUp.selectPolicy }}
      stabilizationWindowSeconds: {{ .behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .behavior.scaleUp.policies | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}