// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: voice_lover_admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminVoiceLoverAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime   uint64                      `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PubUid       uint32                      `protobuf:"varint,3,opt,name=pub_uid,json=pubUid,proto3" json:"pub_uid,omitempty"`
	PubUserName  string                      `protobuf:"bytes,4,opt,name=pub_user_name,json=pubUserName,proto3" json:"pub_user_name,omitempty"`
	Broker       string                      `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	Resource     string                      `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	Covers       []string                    `protobuf:"bytes,7,rep,name=covers,proto3" json:"covers,omitempty"`
	Source       int32                       `protobuf:"varint,8,opt,name=source,proto3" json:"source,omitempty"`
	Desc         string                      `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	Labels       []string                    `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	AuditStatus  int32                       `protobuf:"varint,11,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	OpUid        uint64                      `protobuf:"varint,12,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
	EditDubs     []*AdminVoiceLoverAudioEdit `protobuf:"bytes,13,rep,name=edit_dubs,json=editDubs,proto3" json:"edit_dubs,omitempty"`
	EditContents []*AdminVoiceLoverAudioEdit `protobuf:"bytes,14,rep,name=edit_contents,json=editContents,proto3" json:"edit_contents,omitempty"`
	EditPosts    []*AdminVoiceLoverAudioEdit `protobuf:"bytes,15,rep,name=edit_posts,json=editPosts,proto3" json:"edit_posts,omitempty"`
	EditCovers   []*AdminVoiceLoverAudioEdit `protobuf:"bytes,16,rep,name=edit_covers,json=editCovers,proto3" json:"edit_covers,omitempty"`
}

func (x *AdminVoiceLoverAudio) Reset() {
	*x = AdminVoiceLoverAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_lover_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminVoiceLoverAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminVoiceLoverAudio) ProtoMessage() {}

func (x *AdminVoiceLoverAudio) ProtoReflect() protoreflect.Message {
	mi := &file_voice_lover_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminVoiceLoverAudio.ProtoReflect.Descriptor instead.
func (*AdminVoiceLoverAudio) Descriptor() ([]byte, []int) {
	return file_voice_lover_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminVoiceLoverAudio) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetPubUid() uint32 {
	if x != nil {
		return x.PubUid
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetPubUserName() string {
	if x != nil {
		return x.PubUserName
	}
	return ""
}

func (x *AdminVoiceLoverAudio) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *AdminVoiceLoverAudio) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AdminVoiceLoverAudio) GetCovers() []string {
	if x != nil {
		return x.Covers
	}
	return nil
}

func (x *AdminVoiceLoverAudio) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AdminVoiceLoverAudio) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AdminVoiceLoverAudio) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetOpUid() uint64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *AdminVoiceLoverAudio) GetEditDubs() []*AdminVoiceLoverAudioEdit {
	if x != nil {
		return x.EditDubs
	}
	return nil
}

func (x *AdminVoiceLoverAudio) GetEditContents() []*AdminVoiceLoverAudioEdit {
	if x != nil {
		return x.EditContents
	}
	return nil
}

func (x *AdminVoiceLoverAudio) GetEditPosts() []*AdminVoiceLoverAudioEdit {
	if x != nil {
		return x.EditPosts
	}
	return nil
}

func (x *AdminVoiceLoverAudio) GetEditCovers() []*AdminVoiceLoverAudioEdit {
	if x != nil {
		return x.EditCovers
	}
	return nil
}

type AdminVoiceLoverAudioEdit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *AdminVoiceLoverAudioEdit) Reset() {
	*x = AdminVoiceLoverAudioEdit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_lover_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminVoiceLoverAudioEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminVoiceLoverAudioEdit) ProtoMessage() {}

func (x *AdminVoiceLoverAudioEdit) ProtoReflect() protoreflect.Message {
	mi := &file_voice_lover_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminVoiceLoverAudioEdit.ProtoReflect.Descriptor instead.
func (*AdminVoiceLoverAudioEdit) Descriptor() ([]byte, []int) {
	return file_voice_lover_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminVoiceLoverAudioEdit) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AdminVoiceLoverAudioEdit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminVoiceLoverAudioEdit) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type RespAdminVoiceLoverAudioList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audios []*AdminVoiceLoverAudio `protobuf:"bytes,1,rep,name=audios,proto3" json:"audios,omitempty"`
	Total  int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RespAdminVoiceLoverAudioList) Reset() {
	*x = RespAdminVoiceLoverAudioList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_lover_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespAdminVoiceLoverAudioList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAdminVoiceLoverAudioList) ProtoMessage() {}

func (x *RespAdminVoiceLoverAudioList) ProtoReflect() protoreflect.Message {
	mi := &file_voice_lover_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAdminVoiceLoverAudioList.ProtoReflect.Descriptor instead.
func (*RespAdminVoiceLoverAudioList) Descriptor() ([]byte, []int) {
	return file_voice_lover_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RespAdminVoiceLoverAudioList) GetAudios() []*AdminVoiceLoverAudio {
	if x != nil {
		return x.Audios
	}
	return nil
}

func (x *RespAdminVoiceLoverAudioList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RespAdminVoiceLoverAudioDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio *AdminVoiceLoverAudio `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
}

func (x *RespAdminVoiceLoverAudioDetail) Reset() {
	*x = RespAdminVoiceLoverAudioDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_lover_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespAdminVoiceLoverAudioDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAdminVoiceLoverAudioDetail) ProtoMessage() {}

func (x *RespAdminVoiceLoverAudioDetail) ProtoReflect() protoreflect.Message {
	mi := &file_voice_lover_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAdminVoiceLoverAudioDetail.ProtoReflect.Descriptor instead.
func (*RespAdminVoiceLoverAudioDetail) Descriptor() ([]byte, []int) {
	return file_voice_lover_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RespAdminVoiceLoverAudioDetail) GetAudio() *AdminVoiceLoverAudio {
	if x != nil {
		return x.Audio
	}
	return nil
}

var File_voice_lover_admin_proto protoreflect.FileDescriptor

var file_voice_lover_admin_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc8, 0x04,
	0x0a, 0x14, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65,
	0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x75, 0x62, 0x55, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x70, 0x75, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x75, 0x64, 0x69,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x09, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x64, 0x75, 0x62, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63,
	0x65, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x08, 0x65, 0x64, 0x69, 0x74, 0x44, 0x75, 0x62, 0x73, 0x12, 0x41, 0x0a, 0x0d, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x64, 0x69, 0x74, 0x52, 0x0c,
	0x65, 0x64, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3b, 0x0a, 0x0a,
	0x65, 0x64, 0x69, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x64, 0x69, 0x74, 0x52, 0x09,
	0x65, 0x64, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x65, 0x64, 0x69,
	0x74, 0x5f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f,
	0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x64, 0x69, 0x74, 0x52, 0x0a, 0x65, 0x64,
	0x69, 0x74, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x22, 0x58, 0x0a, 0x18, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x45, 0x64, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x22, 0x66, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x70, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x06, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x50, 0x0a, 0x1e, 0x52, 0x65,
	0x73, 0x70, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65,
	0x72, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2e, 0x0a, 0x05,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76, 0x65, 0x72,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x61, 0x6f, 0x6c,
	0x61, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x72, 0x62, 0x70, 0x2d, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_voice_lover_admin_proto_rawDescOnce sync.Once
	file_voice_lover_admin_proto_rawDescData = file_voice_lover_admin_proto_rawDesc
)

func file_voice_lover_admin_proto_rawDescGZIP() []byte {
	file_voice_lover_admin_proto_rawDescOnce.Do(func() {
		file_voice_lover_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_voice_lover_admin_proto_rawDescData)
	})
	return file_voice_lover_admin_proto_rawDescData
}

var file_voice_lover_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_voice_lover_admin_proto_goTypes = []interface{}{
	(*AdminVoiceLoverAudio)(nil),           // 0: pb.AdminVoiceLoverAudio
	(*AdminVoiceLoverAudioEdit)(nil),       // 1: pb.AdminVoiceLoverAudioEdit
	(*RespAdminVoiceLoverAudioList)(nil),   // 2: pb.RespAdminVoiceLoverAudioList
	(*RespAdminVoiceLoverAudioDetail)(nil), // 3: pb.RespAdminVoiceLoverAudioDetail
}
var file_voice_lover_admin_proto_depIdxs = []int32{
	1, // 0: pb.AdminVoiceLoverAudio.edit_dubs:type_name -> pb.AdminVoiceLoverAudioEdit
	1, // 1: pb.AdminVoiceLoverAudio.edit_contents:type_name -> pb.AdminVoiceLoverAudioEdit
	1, // 2: pb.AdminVoiceLoverAudio.edit_posts:type_name -> pb.AdminVoiceLoverAudioEdit
	1, // 3: pb.AdminVoiceLoverAudio.edit_covers:type_name -> pb.AdminVoiceLoverAudioEdit
	0, // 4: pb.RespAdminVoiceLoverAudioList.audios:type_name -> pb.AdminVoiceLoverAudio
	0, // 5: pb.RespAdminVoiceLoverAudioDetail.audio:type_name -> pb.AdminVoiceLoverAudio
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_voice_lover_admin_proto_init() }
func file_voice_lover_admin_proto_init() {
	if File_voice_lover_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_voice_lover_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminVoiceLoverAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voice_lover_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminVoiceLoverAudioEdit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voice_lover_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespAdminVoiceLoverAudioList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voice_lover_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespAdminVoiceLoverAudioDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_voice_lover_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_voice_lover_admin_proto_goTypes,
		DependencyIndexes: file_voice_lover_admin_proto_depIdxs,
		MessageInfos:      file_voice_lover_admin_proto_msgTypes,
	}.Build()
	File_voice_lover_admin_proto = out.File
	file_voice_lover_admin_proto_rawDesc = nil
	file_voice_lover_admin_proto_goTypes = nil
	file_voice_lover_admin_proto_depIdxs = nil
}
