{{- if $.Values.hpa.enabled }}
{{- with $.Values.hpa }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    role: http
    {{- toYaml $.Values.global.labels | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.deployment.name }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  {{- if .metrics.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .metrics.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if .metrics.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .metrics.memory.targetAverageUtilization }}
  {{- end }}
  {{- if .behavior.enabled }}
  {{- with .behavior }}
  behavior:
    {{- if .scaleDown.enabled }}
    scaleDown:
      stabilizationWindowSeconds: {{ .scaleDown.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .scaleDown.policies | nindent 8 }}
    {{- end }}
    {{- if .scaleUp.enabled }}
    scaleUp:
      selectPolicy: {{ .scaleUp.selectPolicy }}
      stabilizationWindowSeconds: {{ .scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .scaleUp.policies | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}