debug: false
# 默认配置
deployment:
  debug: false
  graceExit:
    enabled: true
    timeoutSeconds: 10
  image:
    repository: slp-acr-registry-vpc.cn-hangzhou.cr.aliyuncs.com/slp/slp-app-rpc
    tag: latest
    pullPolicy: IfNotPresent
  annotations:
    slp.k8s.io/recreateRevision: "2"
  replicas: 2
  resources:
    requests:
      memory: "200Mi"
      cpu: "0.1"
    limits:
      memory: "200Mi"
      cpu: "0.1"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
  strategy:
    enabled: true
    type: RollingUpdate
    rollingUpdate:
      enabled: true
      maxSurge: "25%"
      maxUnavailable: "25%"
  lifecycle:
    enabled: true
    preStop:
      enabled: true
  # 节点亲和性配置
  affinity:
    enabled: true
    nodeAffinity:
      repository:
        weight: 50
        values:
          - app
      serverMode:
        weight: 100
        values:
          - rpc
    # Pod 反亲和性配置
    podAntiAffinity:
      weight: 100
      values:
  gfLoggerVolume:
    enabled: false
  # 全局配置
  imagePullSecrets:
    enabled: false
    secrets:
      - name: "ivan-personal-acr"

storage:
  enabled: false
  maxSize: 500Mi

# 存储配置
gfConfigMap:
  name: gf-gcfg-file
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  metrics:
    cpu:
      enabled: true
      targetAverageUtilization: 70
    memory:
      enabled: true
      targetAverageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 10
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 10
          periodSeconds: 30

# 启用的命令列表
enabledRpcs:
  - voice-lover-admin
  - voice-lover-main