debug: false
global:
  enabled: true
  port: 8081
  labels:
    app: slp-functor-http
# 默认配置
deployment:
  enabled: true
  debug: false
  name: slp-functor-http-deploy
  graceExit:
    enabled: true
    timeoutSeconds: 10
  image:
    repository: slp-acr-registry-vpc.cn-hangzhou.cr.aliyuncs.com/slp/slp-functor-http
    tag: chenjunjun2-ola.master.20250425-184117
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "200m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
  strategy:
    enabled: true
    type: RollingUpdate
    rollingUpdate:
      enabled: true
      maxSurge: "25%"
      maxUnavailable: "25%"
  lifecycle:
    enabled: true
    preStop:
      enabled: true
  # 节点亲和性配置
  affinity:
    enabled: true
    nodeAffinity:
      repository:
        weight: 50
        values:
          - app
      serverMode:
        weight: 100
        values:
          - http
    # Pod 反亲和性配置
    podAntiAffinity:
      weight: 100
      values:
  gfLoggerVolume:
    enabled: false
  # 全局配置
  imagePullSecrets:
    enabled: false
    secrets:
      - name: "ivan-personal-acr"
  tcpdump:
    enabled: false
storage:
  enabled: false
  maxSize: 500Mi
# 存储配置
gfConfigMap:
  name: gf-gcfg-file
hpa:
  enabled: true
  name: slp-functor-http-hpa
  minReplicas: 2
  maxReplicas: 50
  metrics:
    cpu:
      enabled: true
      targetAverageUtilization: 70
    memory:
      enabled: true
      targetAverageUtilization: 80
  behavior:
    scaleDown:
      enabled: true
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 10
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      enabled: true
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 10
          periodSeconds: 30
pdb:
  enabled: true
  name: slp-functor-http-pdb
  minAvailable: 2
service:
  enabled: true
  name: slp-functor-http-internal-svc
  type: ClusterIP
