# HTTP Server.
[server]
	Address        = ":8082"
	ServerRoot     = "public"
	ServerAgent    = "we are family"
	LogPath        = "/tmp/log/server"
	AccessLogEnabled = true
	ErrorLogEnabled = true
	PProfEnabled   = true
	Graceful	       = true
	RunMode	       = "dev"
	Language		   = ["zh-cn"]
	TraceName	   = "test"

# Logger configurations.
[logger]
    Path   = "/tmp/log/server"
    Level  = "all"
    Stdout = true
    CtxKeys = ["TraceId"]

# Template view configurations.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"

[comon-const-param]
	IpServ="serv-ip.banban.private"
	#一分钟内的点歌频率限制
	TemFrequencyNum = 20
	#tem用户池子的最大数量
	TemUserPoolMaxNum = 1000
[algo-limit]
	RateLimit = 10


# Database configurations.
[database]
	#读写分离主库
    [[database.default]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/functor"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "master"
    #读写分离从库
    [[database.default]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/functor"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "slave"
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true
	#读写分离主库
    [[database.xianshi]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "master"
    #读写分离从库
    [[database.xianshi]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "slave"
	#rush库
	[[database.rush]]
		type = "bbsql"
		link = "root:root@tcp(192.168.11.24:3306)/rush"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#联盟库
	[[database.bbu]]
		type = "bbsql"
		link = "root:root@tcp(192.168.11.24:3306)/banban_union"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#数据统计库
	[[database.banban]]
		type = "bbsql"
		link = "root:root@tcp(192.168.11.24:3306)/banban"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#配置库
	[[database.config]]
		type = "bbsql"
		link = "root:root@tcp(192.168.11.24:3306)/config"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#xsst库
	[[database.xsst]]
		type = "bbsql"
		link = "root:root@tcp(192.168.11.24:3306)/xsst"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
    #朋友圈主库
    [[database.circle]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "master"
    #朋友圈从库
    [[database.circle]]
        type = "bbsql"
        link = "root:root@tcp(192.168.11.24:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "slave"
     [[database.functor]]
            type = "bbsql"
            link = "root:root@tcp(192.168.11.24:3306)/functor"
            charset = "utf8mb4"
            debug = true
            maxIdle = 1
            maxOpen = 100
            maxLifetime = 30
            role = "master"
        #朋友圈从库
     [[database.functor]]
            type = "bbsql"
            link = "root:root@tcp(192.168.11.24:3306)/functor"
            charset = "utf8mb4"
            debug = true
            maxIdle = 1
            maxOpen = 100
            maxLifetime = 30
            role = "slave"

# go-redis 配置
[go-redis]
	[go-redis.default]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.cache]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.cache_old]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""

	[go-redis.room]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.user]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.mate]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	#存储用户基本信息，令牌基本信息，房间基本信息
	[go-redis.rpc_cache]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	#匹配redis，先放在cache，如果后期数据量大方便迁移
    [go-redis.match]
    	Host = "192.168.11.24"
    	Port = 6379
    	Password = ""
	[go-redis.search]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.record]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""
	[go-redis.es]
		Host = "192.168.11.24"
		Port = 6379
		Password = ""

# go-nsq 配置
[go-nsq]
	lookup = ["192.168.11.24:4161"]
	nsq = ["192.168.11.24:4150"]
	default = ["192.168.11.24:4150"]
	circle = ["192.168.11.24:4150"]

[go-es]
	[go-es.user]
		Host = "192.168.11.24"
		Port = 9200
		User = ""
		Password = ""
	[go-es.rush]
		Host = "192.168.11.24"
		Port = 9200
		User = ""
		Password = ""
	[go-es.es_new]
		Host = "192.168.11.24"
		Port = 9200
		User = ""
		Password = ""
	[go-es.es_vpc]
		Host = "192.168.11.24"
		Port = 9200
		User = ""
		Password = ""

[go-kafka]
	[go-kafka.default]
		Host = ["192.168.11.24:9092"]
		#务必查看 github.com/Shopify/sarama utils.go 版本号，
		Version = "0.10.2.1"

[http-service]
	[http-service.im.publish]
		URI = "http://47.114.166.11:6080/imapi/message/private/publish"
		TimeoutMs = 500 #单位ms
		Retry = 2
		PrintResponse = true
	[http-service.push.report]
		URI = "http://47.114.166.11:6080/push/v1/save_device_token"
		TimeoutMs = 1000 #单位ms
		Retry = 2
		PrintResponse = true
	[http-service.im.checkdirty]
		URI = "http://47.114.166.11:6080/filter/checkdirty"
		TimeoutMs = 1000 #单位ms
		Retry = 2
		PrintResponse = true
	[http-service.im.dirty]
		URI = "http://47.114.166.11:6080/filter/dirty"
		TimeoutMs = 1000 #单位ms
		Retry = 2
		PrintResponse = true
	[http-service.weixin.pdytech]
		URI = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=6fd2f3d5-722c-47dc-a3a8-9f838d68d90d"
		TimeoutMs = 500 #单位ms
		Retry = 1
		PrintResponse = true

[rpc]
	[rpc.discover]
		Type = "consul"
		Addr = ["127.0.0.1:8500"]
		# Addr = ["120.26.196.226:6545"]
		Path = "/slp"

[go-rocketmq]
    [default]
        EndPoint = "192.168.11.24:8082"
        AccessKey = ""
        AccessSecret = ""


# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
		link   = "mysql:root:root@tcp(172.16.1.63:3306)/config"
		#link   = "mysql:root:root@tcp(172.16.1.63:3306)/xianshi"
		jsonCase = "Snake"
	[[gfcli.gen.pbentity]]
		link    = "mysql:root:root@tcp(172.16.1.63:3306)/config"
		#link    = "mysql:root:root@tcp(172.16.1.63:3306)/xianshi"
		path    = "proto"
		jsonCase = "Snake"
		package = "pb"
		option 	= "option go_package = \"../app/pb\";"
