debug: false

# 默认配置
deployment:
  debug: false
  annotations:
    slp.k8s.io/recreateRevision: "2"
  image:
    repository: slp-acr-registry-vpc.cn-hangzhou.cr.aliyuncs.com/slp/slp-app-cmd
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "150Mi"
      cpu: "30m"
    limits:
      memory: "150Mi"
      cpu: "100m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
  strategy:
    enabled: true
    type: RollingUpdate
    rollingUpdate:
      enabled: true
      maxSurge: "25%"
      maxUnavailable: "25%"
  # 节点亲和性配置
  affinity:
    enabled: true
    nodeAffinity:
      repository:
        weight: 50
        values:
          - app
      serverMode:
        weight: 100
        values:
          - cmd
    # Pod 反亲和性配置
    podAntiAffinity:
      weight: 100
      values:
  gfLoggerVolume:
    enabled: false
  # 全局配置
  imagePullSecrets:
    enabled: false
    secrets:
      - name: "ivan-personal-acr"

storage:
  enabled: false
  maxSize: 500Mi

systemInfoReport:
  enabled: true
  name: slp-cmd-systeminfo-report
  tag: latest
  priorityClassName: PreemptLowerPriority
  periodSeconds: 30
  imagePullSecrets:
    enabled: false
    secrets:
      - name: "ivan-personal-acr"
  resources:
    requests:
      memory: "150Mi"
      cpu: "0.1"
    limits:
      memory: "150Mi"
      cpu: "0.1"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3

# 存储配置
gfConfigMap:
  name: gf-gcfg-file

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  metrics:
    cpu:
      enabled: true
      targetAverageUtilization: 70
    memory:
      enabled: true
      targetAverageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 10
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 10
          periodSeconds: 30

# 启用的命令列表
enabledCmds:
  - binlog-start
  - user-profile-run
  - aichat-run
  - achieve-consume
  - sweet-album-start
  - anchor-main
  - argus-start
  - artcenter-trans-arttransfer
  - cache-aggregation-aggregation
  - cache-chatroom-chatroom
  - cache-profile-profile
  - cache-codec-codec
  - goddess-car-consume
  - gate-msg-consume
  - delay-msg-consume
  - giftreward-new-giftreward
  - giftwall-giftwall
  - login-consume-consume
  - room-data-roomdata
  - room-tag-roomtag
  - roomoperation-consume-consume
  - roomvip-payment
  - specialattention-consume-consume
  - starsign-consume
  - travel-consume
  - treattask-consume-consume
  - user-start
  - user-binloglisten-binloglisten
  - user-gift-syhandle
  - gift-book-rank-giftbookrank
  - artcenter-sync-artlistsync
  - autochat-consume-consume
  - box-gift-run
  - hour-rank-start
  - exhibition-start
  - facedet-startconsume
  - group-syhandle
  - hearthat-start
  - match-match
  - musicorder-start
  - pay-start
  - pay-callback
  - purrecommend-start
  - rankmatch-consume
  - room-data-sum-roomdatahandle
  - smartgreet-consume-consume
  - smartgreet-cron
  - sms-sms
  - viability-start
  - wakeup-push-run
  - pretend-run
  - common-gift-send-consume
  - square-run
  - room-event-consume
  - mission-start
  - giftRank-run
  - musicParty-start
  - gs-birthday-start
  - full-screen-consume
  - katouch-start
  - user-follow-follow
  - roomredpacket-run
  - fans-run
  - room-proc-consume
  - zodiacpai-start
  - relation-run
  - search-consume
  - task-starttask
  - chategg-consume
  - cloudview-consume
  - confess-consume
  - cphouse-consume
  - defendrank-consume
  - familiar-familiar
  - giftimpress-consume
  - nobility-pass-start
  - ai-anchor-run
  - worldredpacket-run
