{{- /*
在模板开始处添加调试信息
*/}}
{{- range .Values.enabledCmds }}
{{- $ctx := dict "name" . "Files" $.Files }}
{{- $cmdValues := fromYaml (include "cmds.getValues" $ctx) }}
{{- $mergedValues := merge
    (dict)
    ($.Values.hpa | default dict)
    ($cmdValues.hpa | default dict)
}}
{{- $cmdName := $cmdValues.deployment.name | lower }}
{{- $cmdAction := $cmdValues.deployment.action | lower }}
{{- $cmdInstance := printf "slp-functor-cmd-%s-%s" $cmdName $cmdAction }}
{{- /* 调试信息 */ -}}
{{- if $.Values.debug }}
{{- printf "\nDebug info for command: %s" . | nindent 0 }}
{{- printf "\nCommand Values:" | nindent 0 }}
{{- toYaml $cmdValues | nindent 2 }}
{{- printf "\nMerged Values:" | nindent 0 }}
{{- toYaml $mergedValues | nindent 2 }}
{{- end }}
---
{{- if $mergedValues.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $cmdInstance }}-hpa
  namespace: {{ $.Release.Namespace }}

{{- with $mergedValues }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $cmdInstance }}-deploy

  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  {{- if .metrics.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .metrics.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if .metrics.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .metrics.memory.targetAverageUtilization }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .behavior.scaleDown.policies | nindent 8 }}
    scaleUp:
      selectPolicy: {{ .behavior.scaleUp.selectPolicy }}
      stabilizationWindowSeconds: {{ .behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- toYaml .behavior.scaleUp.policies | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
