deployment:
  name: "voice_lover_admin"
  image:
    tag: chenjunjun2-ola.master.20250425-190318
  resources:
    requests:
      memory: "100Mi"
      cpu: "20m"
    limits:
      memory: "100Mi"
      cpu: "1000m"