deployment:
  name: "voice_lover_main"
  image:
    tag: chenjunjun2-ola.master.20250428-174401
  resources:
    requests:
      memory: "100Mi"
      cpu: "60m"
    limits:
      memory: "100Mi"
      cpu: "60m"