deployment:
  name: "voice_lover_admin"
  image:
    tag: chenjunjun2-ola.master.20250428-190006
  resources:
    requests:
      memory: "100Mi"
      cpu: "30m"
    limits:
      memory: "100Mi"
      cpu: "60m"