deployment:
  name: "voice_lover_main"
  image:
    tag: chengshuo.cs-0428-fixconfig.20250428-180955
  resources:
    requests:
      memory: "100Mi"
      cpu: "60m"
    limits:
      memory: "100Mi"
      cpu: "60m"