deployment:
  name: "voice_lover_admin"
  image:
    tag: chengshuo.cs-0428-updateProto.20250428-185010
  resources:
    requests:
      memory: "100Mi"
      cpu: "60m"
    limits:
      memory: "100Mi"
      cpu: "60m"